In [72]:
import pandas as pd
cc_apps = pd.read_csv("cc_approvals.data")

In [73]:
cc_apps.head(5)

   b  30.83      0  u  g  w  v  1.25  t t.1  01  f g.1  00202  0.1  +
0  a  58.67  4.460  u  g  q  h  3.04  t   t   6  f   g  00043  560  +
1  a  24.50  0.500  u  g  q  h  1.50  t   f   0  f   g  00280  824  +
2  b  27.83  1.540  u  g  w  v  3.75  t   t   5  t   g  00100    3  +
3  b  20.17  5.625  u  g  w  v  1.71  t   f   0  f   s  00120    0  +
4  b  32.08  4.000  u  g  m  v  2.50  t   f   0  t   g  00360    0  +

In [74]:
cc_apps_description = cc_apps.describe()
print(cc_apps_description)

                0        1.25          01            0.1
count  689.000000  689.000000  689.000000     689.000000
mean     4.765631    2.224819    2.402032    1018.862119
std      4.978470    3.348739    4.866180    5213.743149
min      0.000000    0.000000    0.000000       0.000000
25%      1.000000    0.165000    0.000000       0.000000
50%      2.750000    1.000000    0.000000       5.000000
75%      7.250000    2.625000    3.000000     396.000000
max     28.000000   28.500000   67.000000  100000.000000

In [75]:
cc_apps_info = cc_apps.info()
print(cc_apps_info)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 689 entries, 0 to 688
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   b       689 non-null    object
 1   30.83   689 non-null    object
 2   0       689 non-null    float64
 3   u       689 non-null    object
 4   g       689 non-null    object
 5   w       689 non-null    object
 6   v       689 non-null    object
 7   1.25    689 non-null    float64
 8   t       689 non-null    object
 9   t.1     689 non-null    object
 10  01      689 non-null    int64
 11  f       689 non-null    object
 12  g.1     689 non-null    object
 13  00202   689 non-null    object
 14  0.1     689 non-null    int64
 15  +       689 non-null    object
dtypes: float64(2), int64(2), object(12)
memory usage: 86.2+ KB
None

In [77]:
cc_apps.tail(17)

     b  30.83       0  u  g   w   v   1.25  t t.1  01  f g.1  00202  0.1  +
672  ?  29.50   2.000  y  p   e   h  2.000  f   f   0  f   g  00256   17  -
673  a  37.33   2.500  u  g   i   h  0.210  f   f   0  f   g  00260  246  -
674  a  41.58   1.040  u  g  aa   v  0.665  f   f   0  f   g  00240  237  -
675  a  30.58  10.665  u  g   q   h  0.085  f   t  12  t   g  00129    3  -
676  b  19.42   7.250  u  g   m   v  0.040  f   t   1  f   g  00100    1  -
677  a  17.92  10.210  u  g  ff  ff  0.000  f   f   0  f   g  00000   50  -
678  a  20.08   1.250  u  g   c   v  0.000  f   f   0  f   g  00000    0  -
679  b  19.50   0.290  u  g   k   v  0.290  f   f   0  f   g  00280  364  -
680  b  27.83   1.000  y  p   d   h  3.000  f   f   0  f   g  00176  537  -
681  b  17.08   3.290  u  g   i   v  0.335  f   f   0  t   g  00140    2  -
682  b  36.42   0.750  y  p   d   v  0.585  f   f   0  f   g  00240    3  -
683  b  40.58   3.290  u  g   m   v  3.500  f   f   0  t   s  00400    0  -
684  b  21.08  10.085  y  p   e   h  1.250  f   f   0  f   g  00260    0  -
685  a  22.67   0.750  u  g   c   v  2.000  f   t   2  t   g  00200  394  -
686  a  25.25  13.500  y  p  ff  ff  2.000  f   t   1  t   g  00200    1  -
687  b  17.92   0.205  u  g  aa   v  0.040  f   f   0  f   g  00280  750  -
688  b  35.00   3.375  u  g   c   h  8.290  f   f   0  t   g  00000    0  -

In [78]:
import numpy as np

cc_apps.replace('?', 'NaN')

     b  30.83       0  u  g   w   v  1.25  t t.1  01  f g.1  00202  0.1  +
0    a  58.67   4.460  u  g   q   h  3.04  t   t   6  f   g  00043  560  +
1    a  24.50   0.500  u  g   q   h  1.50  t   f   0  f   g  00280  824  +
2    b  27.83   1.540  u  g   w   v  3.75  t   t   5  t   g  00100    3  +
3    b  20.17   5.625  u  g   w   v  1.71  t   f   0  f   s  00120    0  +
4    b  32.08   4.000  u  g   m   v  2.50  t   f   0  t   g  00360    0  +
..  ..    ...     ... .. ..  ..  ..   ... ..  ..  .. ..  ..    ...  ... ..
684  b  21.08  10.085  y  p   e   h  1.25  f   f   0  f   g  00260    0  -
685  a  22.67   0.750  u  g   c   v  2.00  f   t   2  t   g  00200  394  -
686  a  25.25  13.500  y  p  ff  ff  2.00  f   t   1  t   g  00200    1  -
687  b  17.92   0.205  u  g  aa   v  0.04  f   f   0  f   g  00280  750  -
688  b  35.00   3.375  u  g   c   h  8.29  f   f   0  t   g  00000    0  -

[689 rows x 16 columns]

In [79]:
cc_apps.fillna(cc_apps.mean(), inplace = True)
print(cc_apps.isnull().sum())

b        0
30.83    0
0        0
u        0
g        0
w        0
v        0
1.25     0
t        0
t.1      0
01       0
f        0
g.1      0
00202    0
0.1      0
+        0
dtype: int64

In [81]:
for col in cc_apps.columns:
    if cc_apps[col].dtypes == 'object':
        cc_apps = cc_apps.fillna(cc_apps[col].value_counts().index[0])
print(cc_apps.isnull().sum())

b        0
30.83    0
0        0
u        0
g        0
w        0
v        0
1.25     0
t        0
t.1      0
01       0
f        0
g.1      0
00202    0
0.1      0
+        0
dtype: int64

In [84]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for col in cc_apps.columns.values:
    if cc_apps[col].dtypes == 'object':
        cc_apps[col] = le.fit_transform(cc_apps[col])

In [85]:
cc_apps

     b  30.83       0  u  g   w  v  1.25  t  t.1  01  f  g.1  00202  0.1  +
0    1    327   4.460  2  1  11  4  3.04  1    1   6  0    0     11  560  0
1    1     89   0.500  2  1  11  4  1.50  1    0   0  0    0     95  824  0
2    2    125   1.540  2  1  13  8  3.75  1    1   5  1    0     31    3  0
3    2     43   5.625  2  1  13  8  1.71  1    0   0  0    2     37    0  0
4    2    167   4.000  2  1  10  8  2.50  1    0   0  1    0    114    0  0
..  ..    ...     ... .. ..  .. ..   ... ..  ...  .. ..  ...    ...  ... ..
684  2     52  10.085  3  3   5  4  1.25  0    0   0  0    0     89    0  1
685  1     71   0.750  2  1   2  8  2.00  0    1   2  1    0     67  394  1
686  1     97  13.500  3  3   6  3  2.00  0    1   1  1    0     67    1  1
687  2     20   0.205  2  1   1  8  0.04  0    0   0  0    0     95  750  1
688  2    196   3.375  2  1   2  4  8.29  0    0   0  1    0      0    0  1

[689 rows x 16 columns]

In [86]:
from sklearn.model_selection import train_test_split
cc_apps = cc_apps.drop([11,13])
cc_apps = cc_apps.values
X,y = cc_apps[:,0:13], cc_apps[:,13]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42, test_size = 0.33)

In [106]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range = (0,1))
rescaledX_train = scaler.fit_transform(X_train)
rescaledX_test = scaler.fit_transform(X_test)

In [114]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(solver='lbfgs', max_iter=1000)
logreg.fit(rescaledX_train, y_train)

LogisticRegression(max_iter=1000)

In [115]:

from sklearn.metrics import confusion_matrix


y_pred = logreg.predict(rescaledX_test)


print("Accuracy of logistic regression classifier: ", logreg.score(rescaledX_test,y_test))


confusion_matrix(y_test,y_pred)

Accuracy of logistic regression classifier:  0.21145374449339208

array([[43,  0,  0, ...,  0,  0,  0],
       [ 1,  0,  0, ...,  0,  0,  0],
       [ 1,  0,  0, ...,  0,  0,  0],
       ...,
       [ 1,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 2,  0,  0, ...,  0,  0,  1]], dtype=int64)

From our confusion matrix we can see that accuracy is pretty low.

Applying grid search and making model better.

In [118]:
from sklearn.model_selection import GridSearchCV
tol = [0.01, 0.001, 0.0001]
max_iter = [100, 150, 200]
param_grid = {'tol':tol, 'max_iter': max_iter}

In [119]:
grid_model = GridSearchCV(logreg,param_grid,cv = 5)
rescaledX = scaler.fit_transform(X)
grid_model_result = grid_model.fit(rescaledX,y)
best_score, best_params = grid_model_result.best_score_, grid_model_result.best_params_
print(best_score, best_params)

C:\Users\Nehali\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:670: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
C:\Users\Nehali\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Nehali\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Nehali\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Nehali\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Nehali\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Nehali\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Nehali\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Nehali\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Nehali\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Nehali\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Nehali\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Nehali\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.18626890934094997 {'max_iter': 100, 'tol': 0.01}

C:\Users\Nehali\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Best Score : 0.186